spring.datasource.url=jdbc:mysql://localhost:3306/sistema_esportivo?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
spring.datasource.username=root
#senha do iago : J49F228@
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080
# Garante servir arquivos estáticos corretamente no JAR
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**
